[build]
  command = "npm run build"
  publish = "dist"         # ou ajuste conforme sua estrutura: frontend/dist, public, etc

[functions]
  directory =
  node_bundler = "esbuild" # Esbuild é mais rápido e amigável pra TypeScript moderno
